# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6693abd16f0ffe47d58c4cd9e46f9dfbc8bc20ee7132da714d83f72a0849a48052ddbcc1f33bb5ad16a6beb1fde74f3387a3fc5147396afcb010ad80bedb7fa8
  domain: "localhost:3000"
  no_reply: 'info@hte.vn'

test:
  secret_key_base: 1989ef4aee275bb4ea32824ac0110642458d35fef59a76297afcdab3cdabe2fc1939104313aa263e95cdc0a7c61ca208dc0f088ba7bd2c59d7343e9e6af9fbf7
  domain: "example.com"
  no_reply: 'info@hte.vn'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  domain: "hte.vn"
  no_reply: 'info@hte.vn'
